version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mall-db-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mall_database
      MYSQL_ROOT_PASSWORD: password123
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: